sudo: false
language: ruby
env:
  - PATH=$HOME/bin:$PATH
install:
  # install newer phantomjs, see https://github.com/travis-ci/travis-ci/issues/3225 for discussion
  - if [ ! -d $HOME/bin ]; then mkdir $HOME/bin; fi
  - curl --location https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 | tar Oxjv phantomjs-2.1.1-linux-x86_64/bin/phantomjs > $HOME/bin/phantomjs
  - chmod +x $HOME/bin/phantomjs
  - scripts/setup
before_script:
  - phantomjs --version
  - bundle exec jekyll serve --detach
script:
  - scripts/test
